# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options


before_script:
  - echo "Make sure all profiles are down and removed"
  - docker builder prune -a -f
  - docker image prune -a -f
  - docker compose --profile tests down --rmi all
  - docker compose --profile pytest down --rmi all
  - docker compose --profile integration-tests down --rmi all
  - docker compose --profile default down

after_script:
  - echo "After script section"
  - docker compose --profile tests down
  - docker compose --profile pytest down --rmi all
  - docker compose --profile integration-tests  down
  - docker compose --profile default down
  - docker builder prune -a -f
  - docker image prune -a -f



#build:
#  stage: build
#  script:
#    - docker compose --profile default build

test1:
  stage: test
  script:
    - docker compose --profile tests build
    - docker compose --profile tests up --exit-code-from frontend-tests

test2:
  stage: test
  script:
    - docker compose --profile pytest build
    - docker compose --profile pytest up --exit-code-from backend-tests

#deploy:
#  stage: deploy
#  script:
#    - echo "Do your deploy here"
    #- docker compose --profile default build
    #- docker compose --profile default up
#  environment: production
